/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lsp_ffmpegdemo_util_AudioUtils */

#ifndef _Included_com_lsp_ffmpegdemo_util_AudioUtils
#define _Included_com_lsp_ffmpegdemo_util_AudioUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lsp_ffmpegdemo_util_AudioUtils
 * Method:    decodeAudio
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lsp_ffmpegdemo_util_AudioUtils_decodeAudio
  (JNIEnv *, jclass, jstring, jstring);

JNIEXPORT void JNICALL Java_com_lsp_ffmpegdemo_util_AudioUtils_play
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
