/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lsp_ffmpegdemo_util_MediaUtils */

#ifndef _Included_com_lsp_ffmpegdemo_util_MediaUtils
#define _Included_com_lsp_ffmpegdemo_util_MediaUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lsp_ffmpegdemo_util_MediaUtils
 * Method:    play
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_lsp_ffmpegdemo_util_MediaUtils_play
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
