/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lsp_ffmpegdemo_util_VideoUtils */

#ifndef _Included_com_lsp_ffmpegdemo_util_VideoUtils
#define _Included_com_lsp_ffmpegdemo_util_VideoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lsp_ffmpegdemo_util_VideoUtils
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lsp_ffmpegdemo_util_VideoUtils_decode
  (JNIEnv *, jclass, jstring, jstring);

JNIEXPORT void JNICALL Java_com_lsp_ffmpegdemo_util_VideoUtils_render
        (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
